import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import MetricTile from "../components/MetricTile";
import { SEQUENTIAL_BLUE, SERIES, sequentialStep } from "../lib/palette";

interface ProjectMeta {
  orders_total: number;
  return_rate: number;
  return_risk_test_roc_auc: number;
  return_risk_threshold: number;
  image_classifier_test_accuracy: number;
  policy_documents: number;
}

interface ThresholdRow {
  threshold: number;
  precision: number;
  recall: number;
  f1: number;
}

interface ImportanceRow {
  feature: string;
  importance: number;
  raw_feature: string;
  importance_mean: number | null;
}

interface ConfusionMatrix {
  class_names: string[];
  matrix: number[][];
}

interface RetrievalQuery {
  query: string;
  precision: number;
  recall: number;
}

interface RetrievalEval {
  per_query: RetrievalQuery[];
  avg_precision_at_3: number;
  avg_recall_at_3: number;
}

async function loadJson<T>(name: string): Promise<T> {
  const res = await fetch(`/reports/${name}`);
  if (!res.ok) throw new Error(`Missing report: ${name}. Run scripts/export_reports.py.`);
  return res.json();
}

export default function Insights() {
  const [meta, setMeta] = useState<ProjectMeta | null>(null);
  const [sweep, setSweep] = useState<ThresholdRow[]>([]);
  const [importance, setImportance] = useState<ImportanceRow[]>([]);
  const [confusion, setConfusion] = useState<ConfusionMatrix | null>(null);
  const [retrieval, setRetrieval] = useState<RetrievalEval | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([
      loadJson<ProjectMeta>("project_meta.json").then(setMeta),
      loadJson<ThresholdRow[]>("part1_threshold_sweep.json").then(setSweep),
      loadJson<ImportanceRow[]>("part1_importance.json").then(setImportance),
      loadJson<ConfusionMatrix>("part2_confusion_matrix.json").then(setConfusion),
      loadJson<RetrievalEval>("part3_retrieval.json").then(setRetrieval),
    ]).catch((err) => setError(err instanceof Error ? err.message : "Failed to load reports."));
  }, []);

  if (error) {
    return (
      <div style={{ padding: 32, color: "var(--status-critical)" }}>
        {error}
      </div>
    );
  }

  return (
    <div style={{ padding: "24px 32px", maxWidth: 980 }}>
      <h1 style={{ fontSize: 18, marginBottom: 4 }}>Model Insights</h1>
      <p style={{ color: "var(--text-muted)", fontSize: 13, marginTop: 0 }}>
        Every number below is read from a report generated by an actual training/evaluation
        run in this repository -- nothing here is invented for the dashboard.
      </p>

      {meta && (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, margin: "20px 0" }}>
          <MetricTile label="Orders in dataset" value={meta.orders_total.toLocaleString()} />
          <MetricTile label="Overall return rate" value={`${(meta.return_rate * 100).toFixed(2)}%`} />
          <MetricTile
            label="Return-risk test ROC-AUC"
            value={meta.return_risk_test_roc_auc.toFixed(4)}
            detail={`t*_rf = ${meta.return_risk_threshold}`}
          />
          <MetricTile
            label="Image classifier accuracy"
            value={`${(meta.image_classifier_test_accuracy * 100).toFixed(2)}%`}
            detail="ResNet-18 transfer learning, held-out test"
          />
        </div>
      )}

      <Section title="Threshold sweep -- Logistic Regression (Part 1, Task 5)">
        <ResponsiveContainer width="100%" height={260}>
          <LineChart data={sweep} margin={{ top: 8, right: 16, bottom: 0, left: 0 }}>
            <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
            <XAxis dataKey="threshold" stroke="var(--text-muted)" fontSize={12} />
            <YAxis stroke="var(--text-muted)" fontSize={12} domain={[0, 1]} />
            <Tooltip contentStyle={{ background: "var(--surface-1)", border: "1px solid var(--border)" }} />
            <Legend />
            <Line type="monotone" dataKey="precision" stroke={SERIES.blue} strokeWidth={2} dot={false} />
            <Line type="monotone" dataKey="recall" stroke={SERIES.orange} strokeWidth={2} dot={false} />
            <Line type="monotone" dataKey="f1" stroke={SERIES.aqua} strokeWidth={2} dot={false} />
          </LineChart>
        </ResponsiveContainer>
      </Section>

      <Section title="Feature importance: impurity vs. permutation (Part 1, Task 7)">
        <ResponsiveContainer width="100%" height={260}>
          <BarChart
            data={importance.map((r) => ({ ...r, name: r.raw_feature }))}
            margin={{ top: 8, right: 16, bottom: 0, left: 0 }}
          >
            <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" />
            <XAxis dataKey="name" stroke="var(--text-muted)" fontSize={11} />
            <YAxis stroke="var(--text-muted)" fontSize={12} />
            <Tooltip contentStyle={{ background: "var(--surface-1)", border: "1px solid var(--border)" }} />
            <Legend />
            <Bar dataKey="importance" name="impurity" fill={SERIES.blue} radius={[4, 4, 0, 0]} />
            <Bar dataKey="importance_mean" name="permutation (test ROC-AUC drop)" fill={SERIES.orange} radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
        <p style={{ fontSize: 12, color: "var(--text-muted)" }}>
          Note how <code>delivery_distance_km</code> and <code>customer_tenure_days</code> rank highly by
          impurity but contribute almost nothing (near-zero or negative) once measured by actual held-out
          performance drop.
        </p>
      </Section>

      {confusion && <ConfusionHeatmap data={confusion} />}

      {retrieval && (
        <Section
          title={`Retrieval evaluation (Part 3, Task 10) -- avg P@3 ${retrieval.avg_precision_at_3}, avg R@3 ${retrieval.avg_recall_at_3}`}
        >
          <table style={{ width: "100%", fontSize: 12, borderCollapse: "collapse" }}>
            <thead>
              <tr style={{ textAlign: "left", color: "var(--text-muted)" }}>
                <th style={{ padding: "4px 8px" }}>Query</th>
                <th style={{ padding: "4px 8px" }}>Precision@3</th>
                <th style={{ padding: "4px 8px" }}>Recall@3</th>
              </tr>
            </thead>
            <tbody>
              {retrieval.per_query.map((q) => (
                <tr key={q.query} style={{ borderTop: "1px solid var(--border)" }}>
                  <td style={{ padding: "6px 8px" }}>{q.query}</td>
                  <td className="mono" style={{ padding: "6px 8px" }}>
                    {q.precision.toFixed(4)}
                  </td>
                  <td className="mono" style={{ padding: "6px 8px" }}>
                    {q.recall.toFixed(4)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>
      )}
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      style={{
        background: "var(--surface-1)",
        border: "1px solid var(--border)",
        borderRadius: 12,
        padding: 18,
        marginBottom: 18,
      }}
    >
      <h2 style={{ fontSize: 14, marginTop: 0, marginBottom: 10 }}>{title}</h2>
      {children}
    </div>
  );
}

function ConfusionHeatmap({ data }: { data: ConfusionMatrix }) {
  const max = Math.max(...data.matrix.flat());
  const cellSize = 34;
  return (
    <Section title="Confusion matrix -- product image classifier (Part 2)">
      <div style={{ overflow: "auto" }}>
        <svg width={cellSize * (data.class_names.length + 1)} height={cellSize * (data.class_names.length + 1) + 20}>
          {data.class_names.map((name, col) => (
            <text
              key={`col-${name}`}
              x={cellSize * (col + 1.5)}
              y={12}
              fontSize={9}
              textAnchor="middle"
              fill="var(--text-muted)"
            >
              {name.slice(0, 4)}
            </text>
          ))}
          {data.matrix.map((row, rowIdx) => (
            <g key={`row-${rowIdx}`}>
              <text
                x={cellSize / 2}
                y={cellSize * (rowIdx + 1) + 20 - cellSize / 2 + 4}
                fontSize={9}
                textAnchor="middle"
                fill="var(--text-muted)"
              >
                {data.class_names[rowIdx].slice(0, 4)}
              </text>
              {row.map((value, colIdx) => (
                <g key={`cell-${rowIdx}-${colIdx}`}>
                  <rect
                    x={cellSize * (colIdx + 1)}
                    y={cellSize * rowIdx + 20}
                    width={cellSize - 2}
                    height={cellSize - 2}
                    rx={3}
                    fill={rowIdx === colIdx ? SEQUENTIAL_BLUE[6] : sequentialStep(value, max)}
                  />
                  <text
                    x={cellSize * (colIdx + 1) + cellSize / 2}
                    y={cellSize * rowIdx + 20 + cellSize / 2 + 4}
                    fontSize={9}
                    textAnchor="middle"
                    fill={value / max > 0.4 ? "white" : "var(--text-primary)"}
                  >
                    {value}
                  </text>
                </g>
              ))}
            </g>
          ))}
        </svg>
      </div>
      <p style={{ fontSize: 12, color: "var(--text-muted)" }}>
        Rows = true class, columns = predicted class. Diagonal cells are the correct predictions.
      </p>
    </Section>
  );
}
